"""Interactive and non-interactive store initialization."""
from __future__ import annotations

import getpass
import logging
import os
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Mapping, Optional

import tomlkit


log = logging.getLogger(__name__)

SUPPORTED_BACKENDS = ("sqlite", "arangodb", "postgres")
_CREDENTIAL_KEYS = frozenset({"auth_password", "password", "secret", "api_key", "token"})


@dataclass(frozen=True)
class InitResult:
    """Outcome of a store initialization."""

    config_path: Path
    backend: str
    verified: bool


def _build_config(backend: str, backend_options: Mapping[str, Any] | None) -> tomlkit.TOMLDocument:
    doc = tomlkit.document()
    doc.add(tomlkit.comment("Memwright store config -- generated by init wizard."))
    doc.add(tomlkit.comment("Secrets should use $ENV_VAR references, not plaintext."))
    doc.add(tomlkit.nl())

    if backend == "sqlite":
        backends = ["sqlite", "chroma", "networkx"]
    else:
        backends = [backend]

    doc["backends"] = backends
    doc["default_token_budget"] = 16000

    if backend_options:
        table = tomlkit.table()
        for key, value in backend_options.items():
            table[key] = value
        doc[backend] = table

    return doc


def _redact_credentials(options: Mapping[str, Any] | None) -> Dict[str, Any] | None:
    """Keep credential-like keys out of the on-disk config."""
    if not options:
        return None
    return {k: v for k, v in options.items() if k not in _CREDENTIAL_KEYS}


def _set_secure_permissions(path: Path) -> None:
    """Chmod 0o600 on Unix; best-effort on other platforms."""
    try:
        os.chmod(path, 0o600)
    except (OSError, NotImplementedError) as exc:
        log.debug("Could not set 0o600 on %s: %s", path, exc)


def _snapshot_dir(path: Path) -> Dict[str, bytes] | None:
    """Capture file contents of `path` for potential restore. Returns None if dir is absent."""
    if not path.exists():
        return None
    snapshot: Dict[str, bytes] = {}
    for child in path.rglob("*"):
        if child.is_file():
            snapshot[str(child.relative_to(path))] = child.read_bytes()
    return snapshot


def _restore_from_snapshot(path: Path, snapshot: Dict[str, bytes] | None) -> None:
    """Delete everything under `path` and restore the snapshot contents."""
    if path.exists():
        shutil.rmtree(path)
    if snapshot is None:
        return
    path.mkdir(parents=True, exist_ok=True)
    for rel_path, data in snapshot.items():
        target = path / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)


def _verify_store(path: Path) -> tuple[bool, str | None]:
    """Open the store and run a health check. Returns (ok, error_message)."""
    try:
        from attestor import AgentMemory

        with AgentMemory(path) as mem:
            if hasattr(mem, "health"):
                mem.health()
            else:
                mem.stats()
        return True, None
    except Exception as exc:
        log.warning("Store health check failed: %s", exc)
        return False, f"{type(exc).__name__}: {exc}"


def init_store(
    path: Path,
    *,
    backend: str = "sqlite",
    backend_options: Optional[Dict[str, Any]] = None,
    verify: bool = False,
) -> InitResult:
    """Create a memwright store with a starter TOML config.

    Credential-like keys in `backend_options` are stripped before write.
    With `verify=True`, the store's side-effect files are rolled back on failure.
    """
    if backend not in SUPPORTED_BACKENDS:
        raise ValueError(
            f"Unsupported backend {backend!r}. Choose from {list(SUPPORTED_BACKENDS)}."
        )

    if backend == "postgres" and not (backend_options or {}).get("url"):
        raise ValueError("postgres backend requires a 'url' in backend_options")

    path.mkdir(parents=True, exist_ok=True)
    config_file = path / "config.toml"
    legacy_json = path / "config.json"
    if config_file.exists() or legacy_json.exists():
        raise FileExistsError(f"Config already exists at {path}")

    pre_snapshot = _snapshot_dir(path) if verify else None

    safe_options = _redact_credentials(backend_options)
    doc = _build_config(backend, safe_options)
    config_file.write_text(tomlkit.dumps(doc))
    _set_secure_permissions(config_file)

    verified = False
    if verify:
        ok, reason = _verify_store(path)
        if not ok:
            _restore_from_snapshot(path, pre_snapshot)
            raise RuntimeError(f"Store health check failed ({reason}); rolled back config")
        verified = True

    return InitResult(config_path=config_file, backend=backend, verified=verified)


def _prompt_port(prompt: str, default: int) -> int:
    while True:
        raw = input(f"{prompt} [{default}]: ").strip() or str(default)
        try:
            return int(raw)
        except ValueError:
            print(f"  '{raw}' is not a valid integer; try again.")


def init_store_interactive(path: Path, *, verify: bool = False) -> InitResult:
    """Prompt for backend choice and credentials, then init."""
    print(f"Initializing memwright store at: {path}")
    print(f"\nAvailable backends: {', '.join(SUPPORTED_BACKENDS)}")
    backend = input("Backend [sqlite]: ").strip() or "sqlite"

    backend_options: Dict[str, Any] = {}
    if backend == "arangodb":
        mode = input("Mode (local/cloud) [local]: ").strip() or "local"
        port = _prompt_port("Port", 8529)
        backend_options = {"mode": mode, "port": port}
        if mode == "cloud":
            backend_options["url"] = input("URL: ").strip()
            backend_options["auth_username"] = (
                input("Username [root]: ").strip() or "root"
            )
            backend_options["auth_password"] = getpass.getpass(
                "Password (or $ENV_VAR): "
            ).strip()
    elif backend == "postgres":
        url = input("URL [postgresql://localhost:5432]: ").strip() or "postgresql://localhost:5432"
        backend_options = {"url": url}

    return init_store(
        path,
        backend=backend,
        backend_options=backend_options or None,
        verify=verify,
    )
